### ISSUE TITLE
there are many "optional" fields in send correction UI

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1279] opened 2022-08-10 23:21 UTC
Problem:
In the send correction UI on both Desktop & Mobile Sites there are many "optional" fields (Name, Phone, Email). 
![Screen Shot 2022-08-10 at 11 05 04 AM](https://user-images.githubusercontent.com/107142453/183984944-e55ca2ca-1164-4215-8a79-a21c2f424b3d.png)

Step to repro:
goto foodoasis.la
goto map view by entering an address or using current location
Click on "details" for any listing
Click "send correction"

Severity 1 - Cosmetic problem only: need not be fixed unless extra time is available on project

Heuristics Violated:
5:  Error prevention
8:  Aesthetic and minimalist design

Recommendations:
Perhaps we don't have to ask the information that we don't need. Or we can make them as required fields.

### Action Items
- [ ] Design mocks up how it would look
- [ ] make change as designed

Note: the issue in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0) (item no. 31) asks to link this to #1131 

This is issue was created from a list of food seeker [issues identified](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit?usp=sharing) by a [heuristic evaluation](https://docs.google.com/presentation/d/1mAQV8V9y1ZoQAgBb_mflU8UAGcRogsVfEgZU-hKVvQ0/edit?usp=sharing) completed by 
[@Gigi P](https://hackforla.slack.com/team/U02KZ8WSHHV) & @ryu-jieun  at the end of last year.

**Comment by itserindean** [comment] 2022-08-10 23:23
I created this with sevrity 1, as described in [the heuristics spreadsheet](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=0)
but I think the severity should be:
0 = I don’t agree that this is a usability problem at all

I think we want the barrier to submitting corrections to be very low--hence only correction is required, but if the submitter wants to submit more information, submitting it parsed into 3 fields is most useful to us and is not a huge burden tos the user and matches how standard form input works across the internet.

**Comment by sei1122** [comment] 2022-08-11 00:19
The issue is related.  
https://github.com/hackforla/food-oasis/issues/1242

We talked to @entrotech and set the requirement to Correction and the rest is optional. As @itserindean mentioned above, we wanted submission to be the minimum possible. 

I think we can close this issue.

**Comment by staceyrebekahscott** [comment] 2022-08-13 05:57
@GigiUxR I am concurring with @itserindean and @sei1122 that this is not a usability issue and is being handled by the related issue #1242 as Seiko mentions. Marking this issue closed. Please advise if you think this should be reopened and addressed.

**Comment by staceyrebekahscott** [comment] 2022-08-13 05:57
Added Impact Sprints 2022 label, as I was considering all Heuristics issues as a priority for the sprints.

**Closed by staceyrebekahscott** 2022-08-13 05:57 UTC
Labels: Research, idea, Feature: Usability, PM: Food Seekers, Impact Sprints 2022

**Comment by GigiUxR** [comment] 2022-08-24 02:02
@staceyrebekahscott @itserindean @sei1122 I agree with closing the issue.
