### ISSUE TITLE
Bug: Typing in a zip code and pressing return results in zero results

### ISSUE THREAD

**Issue by fancyham** [hackforla/food-oasis#1935] opened 2023-12-01 03:37 UTC
#### Describe the bug 

Typing in a zip code and pressing return gives a location error / zero results.  

Why?  It seems we require that user manually select item from the auto-complete, but this is not normal user behavior.

This affects people using keyboards, and those who don't realize we require tapping an autocomplete item.

User's goal: is to have a system smart enough to figure out what they're looking for, like Google or Apple Maps.

#### Steps to reproduce the issue

1. Go to foodoasis.net
2. Type in a zip code "90011", press return
3. You'll get 'Sorry, we don't have any results for this area.', but this is because the site didn't get a properly formatted address.

User will only get results from the address field if they pick something from the autocomplete menu.

#### What's the expected result?

The search results for 9011

#### What's the actual result?

"Sorry, we don't have any results for this area."

#### Additional details / screenshot

Demo of
1. typing in 90011[return] -> no results
2. typing in 90011[then selecting the only autocomplete result] -> results
 
(enable audio)
https://github.com/hackforla/food-oasis/assets/3376957/f0e79f4f-64a6-4f79-b0b3-ed5b723738f2

#### Suggested solution possibilities:

1. If user types and presses return, then choose the first autocomplete option for them automatically. (this seems easiest to do)
2. If user types in something, presses return, then display a dialog asking them to select an address from a list of autocompletes. (i.e. force them to select an autocomplete)

**Comment by fancyham** [comment] 2023-12-01 03:40
From the design team to devs: can you just implement solution #1?  (use the topmost autocomplete if the user hits 'return').  It may not be perfect but it'll solve most of the problem.

Longer term would be to have a more robust autocomplete system that includes organization names:
- #1115

**Comment by entrotech** [comment] 2023-12-05 03:05
@fancyham  Just realized that this seems to be a duplicate of #1679

**Comment by fancyham** [comment] 2023-12-06 05:05
Might be but #1679 wouldn’t auto-complete at all when all five digits were typed, but now that seems to work — (I thought it was taken up by the devs?).  The Return key issue seems the same, though.

**Comment by hanapotski** [comment] 2023-12-12 04:21
this issue is also related > https://github.com/hackforla/food-oasis/issues/1470

**Closed** 2024-01-12 02:27 UTC
Labels: Release Note: Bug, Role: Design UI/UX, Role: Front-end, P-Feature: Map, Feature: Usability, P-Feature: Landing Page, Ready for dev lead, Sprint 05
