### ISSUE TITLE
Possible Migration to AWS

### ISSUE THREAD

**Issue by 93Belen** [hackforla/food-oasis#1944] opened 2023-12-13 16:26 UTC
### Overview
We might want to migrate Food Oasis to AWS so we can use the Hack for LA account.

### Action Items
Add useful info in the comments of this Issue

**Comment by qiqicodes** [comment] 2024-04-12 21:43
Closing this issue, it is duplicate of #1591

**Closed by qiqicodes** 2024-04-12 21:43 UTC
