### ISSUE TITLE
Fix bug where Map page shows three levels of scrollbars

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#625] opened 2020-07-23 00:16 UTC
### Overview
On the map page, at least at some device sizes, there are three levels of vertical scrolling. The screenshot was taken on a Windows laptop with Chrome.

The innermost scrollbar controls the result list, which is ok, the outer two scrollbars should really be combined into a single scrollbar for the whole screen, or, better yet, eliminated entirely.

### Resources/Instructions

![image](https://user-images.githubusercontent.com/9939032/88241221-57206180-cc3e-11ea-9aec-a35292e03042.png)

**Comment by rblaz001** [comment] 2020-08-17 19:43
**Progress Report**

I have been able to remove the redundant scrollbar from the results list. It was caused by having the Footer in a Grid element that was not nested in the main Grid container. I would like to get rid of the other scrollbar and have the footer placed correctly but our current implementation is not properly responsive.

One major fix as side-effect is increase responsiveness in mobile for mapbox. In the live version swiping horizontally on the map is buggy and tends to only be allowed in small increments. This happens because the input is stolen by the surrounding container which begins to scroll. This issue is completely resolved with this fix and the map feels overall way better.

![Screenshot from 2020-08-17 12-29-33](https://user-images.githubusercontent.com/35281980/90436392-6a7bec80-e085-11ea-942e-8a47a0562315.png)

**Issues**

One unintended side effect of placing the footer within the main Grid container is that it is no longer a the bottom of the viewport. Keep in mind that in the live version, the footer is bellow the viewport and must be scrolled down to be reached.

![Screenshot from 2020-08-17 12-34-18](https://user-images.githubusercontent.com/35281980/90436728-0a397a80-e086-11ea-8737-923d57b5db5c.png)

Note: I fixed several warning in the results page that were caused by typos and lack of keys for lists.

**Closed** 2020-08-19 21:16 UTC
Labels: bug, dev: front-end
