### ISSUE TITLE
Incorporate Google Tag Manager into live site

### ISSUE THREAD

**Issue by lizagarrison** [hackforla/food-oasis#433] opened 2020-05-26 23:56 UTC
### Overview
Incorporate Google Tag Manager into live site to set up Google Analytics

### Script

**head**
```
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({‘gtm.start’:
new Date().getTime(),event:‘gtm.js’});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!=‘dataLayer’?‘&l=‘+l:‘’;j.async=true;j.src=
’https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,‘script’,‘dataLayer’,‘GTM-PS74HS2’);</script>
<!-- End Google Tag Manager -->
```

__________________________

**body**
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src=“https://www.googletagmanager.com/ns.html?id=GTM-PS74HS2”
height=“0" width=“0” style=“display:none;visibility:hidden”></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```

**Comment by wesrowe** [comment] 2020-05-27 00:02
@entrotech I did a little quick research, you probably already know React will make it a little less straightforward to add the GTM snippet. This [medium article](https://medium.com/finnovate-io/integrating-google-tag-manager-with-a-react-app-5a8584ee2251) seemed on target to me.

**Comment by wesrowe** [comment] 2020-05-27 02:53
update: @entrotech The live-site codebase still has the code for GTM scripts, they are just commented out. 

So GTM can be easily added back in by:
1. uncommenting the include statements in the <head> and <body> of the main page layout [_default.html](https://github.com/hackforla/food-oasis-la/blob/master/_layouts/default.html).
2. updating the GTM snippets for head and body that are in these /_includes templates: 
   - [google-tag-mgr-head.html](https://github.com/hackforla/food-oasis-la/blob/master/_includes/google-tag-mgr-head.html)
   - [google-tag-mgr-body.html](https://github.com/hackforla/food-oasis-la/blob/master/_includes/google-tag-mgr-body.html)

**Comment by bbovenzi** [comment] 2020-10-21 18:41
Duplicate of #703

**Closed by bbovenzi** 2020-10-21 18:41 UTC
Labels: enhancement
