### ISSUE TITLE
Bug: Sign up for monthly updates link on Donate page gives 404 error

### ISSUE THREAD

**Issue by itserindean** [hackforla/food-oasis#1294] opened 2022-08-18 04:25 UTC
#### Describe the bug 

If a user tries to sign up for our newsletter they get a a 404 missing page error.

#### Steps to reproduce the issue

(if applicable, please specify platform (iOS, Android, Windows, Mac version) and brower)

1. Go to https://foodoasis.la/donate
2. Click on 'Sign Up'
3. See error 

#### What's the expected result?
Expect to get prompted to enter email address for newsletter 
-

(if you have a suggested solution, you can add it here)

We should either fix the link or if no one is writing a monthly update, delete the sign up button

#### What's the actual result?
 missing page error
-

#### Additional details / screenshot
![Screen Shot 2022-08-17 at 9 16 05 PM](https://user-images.githubusercontent.com/107142453/185292752-9d3c3120-7ec7-4c9c-91e9-6f5af7f2874b.png)
![Screen Shot 2022-08-17 at 9 16 12 PM](https://user-images.githubusercontent.com/107142453/185292754-5ec36cf2-4b31-4d57-938f-3ae1a30bf32b.png)

#### Device configuration
- Device:desktop
- OS version:macOS 12.4
- Browser Chrome
- Browser versionVersion 104.0.5112.79

**Comment by staceyrebekahscott** [comment] 2022-08-18 05:49
Moving to Bugs column for immediate review.

**Comment by staceyrebekahscott** [comment] 2022-08-18 06:31
Created issue #1297 to address similar issue. It appears none of the links on the website are currently working.

**Comment by entrotech** [comment] 2022-08-20 00:02
@staceyrebekahscott I changed this to a Product Management Issue.  The problem is that we don't really have a monthly newsletter, and the PMs need to decide if we want to start one, get rid of the reference from our site, or do something else.  The button was linked to a domain that is no longer active, probably managed by Jenny Mikesell.  I don't know if the mailing list was ever implemented. It looks like the domain has expired and was taken over by someone else: https://www.whois.com/whois/foodoasis.us

**Comment by entrotech** [comment] 2022-08-21 01:13
As a (maybe temporary work-around, I commented out the box about signing up for a newsletter:

Before:
![image](https://user-images.githubusercontent.com/9939032/185771236-10315bb3-2ce9-4748-82d7-88c1f5daf491.png)

After:
![image](https://user-images.githubusercontent.com/9939032/185771250-2307ff9c-3bad-4e5b-94f0-97db89bede8e.png)

**Comment by itserindean** [comment] 2022-08-21 07:49
I think this is a great solution until someone is found to write a newsletter.

**Comment by staceyrebekahscott** [comment] 2022-08-22 05:02
I agree. A newsletter is not a priority at this time so removing the option from the site is a good solution. 

Closing this issue.

**Closed by staceyrebekahscott** 2022-08-22 05:02 UTC
Labels: Release Note: Bug, dev, size: 1pt, size: 2pt, Role: Product Management, Feature: Usability, PM: Volunteers
