### ISSUE TITLE
Fix z-index of search dropdown

### ISSUE THREAD

**Issue by bbovenzi** [hackforla/food-oasis#833] opened 2021-01-27 17:57 UTC
Problem: The `Search This Area` button when a user pans the map overlaps with the dropdown of suggested locations when someone is doing a search.

<img width="540" alt="Screen Shot 2021-01-26 at 9 18 33 PM" src="https://user-images.githubusercontent.com/4600967/106032874-a7b5c300-6096-11eb-8201-ea8a1b292ebb.png">

Solution: Check out the zIndex's of both components and make sure its set correctly

**Comment by Coro29** [comment] 2021-01-27 22:25
Hi, had a look and it is because of the z-index's. It can be fixed by reducing the 'search this area' button z-index to 1 to avoid map markers going over it or increasing the z-index of the div that contains the search bar and, meals and partners buttons to 3+.

**Comment by tekielee** [comment] 2021-03-10 07:32
Hi, I just assigned this ticket to myself. I just checked the search. I don't see the "SEARCH THIS AREA" box above the text. Did someone fix this or am I searching in the wrong place? Thanks.

**Comment by tekielee** [comment] 2021-03-12 19:20
It is in food find. I found it. I did a git pull. Got errors on starting the server.

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.9
3 info using node@v14.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle foodoasis-client@1.0.45~prestart: foodoasis-client@1.0.45
6 info lifecycle foodoasis-client@1.0.45~start: foodoasis-client@1.0.45
7 verbose lifecycle foodoasis-client@1.0.45~start: unsafe-perm in lifecycle true
8 verbose lifecycle foodoasis-client@1.0.45~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/mackeno/Documents/programming/hackforla/food-oasis/client/node_modules/.bin:/Users/mackeno/lode/opt/bin:/Users/mackeno/lode/opt/bin:/Users/mackeno/lode/opt/bin:/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Postgres.app/Contents/Versions/latest/bin:/Users/mackeno/Documents/terraform
9 verbose lifecycle foodoasis-client@1.0.45~start: CWD: /Users/mackeno/Documents/programming/hackforla/food-oasis/client
10 silly lifecycle foodoasis-client@1.0.45~start: Args: [ '-c', 'react-scripts start' ]
11 silly lifecycle foodoasis-client@1.0.45~start: Returned: code: 1  signal: null
12 info lifecycle foodoasis-client@1.0.45~start: Failed to exec start script
13 verbose stack Error: foodoasis-client@1.0.45 start: `react-scripts start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid foodoasis-client@1.0.45
15 verbose cwd /Users/mackeno/Documents/programming/hackforla/food-oasis/client
16 verbose Darwin 17.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.15.3
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error foodoasis-client@1.0.45 start: `react-scripts start`
22 error Exit status 1
23 error Failed at the foodoasis-client@1.0.45 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by tekielee** [comment] 2021-03-12 21:11
<img width="709" alt="Screen Shot 2021-03-12 at 11 50 07 AM" src="https://user-images.githubusercontent.com/655205/110998934-75091680-8334-11eb-9e9c-2e4503bcc35a.png">

**Comment by ktjnyc** [comment] 2021-04-02 16:04
Hi, is this resolved or still being worked on?

**Comment by entrotech** [comment] 2021-09-10 00:44
I can't reproduce this issu as of 9/9/2021 on the following devices/browsers:
Windows/Chrome
Windows/Firefox
MacBook/Chrome
MacBook/Safari
MacBook/Firefox
Android/Chrome

**Closed** 2021-09-10 01:34 UTC
Labels: Release Note: Bug, good first issue, Role: Front-end, Feature: Search, Missing: Estimate, Review
