### ISSUE TITLE
Redesign tooltip for Organization Edit Form

### ISSUE THREAD

**Issue by gigicobos** [hackforla/food-oasis#1148] opened 2022-01-12 01:49 UTC
### Overview
As part of the [Heuristic Evaluation Research](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=862594579) the research team recommended the redesign of the tooltips for the Organization Edit Form. Issues  listed below:

- Some tooltips are not accessible as the font and background colors are similar (Black and dark grey). 
- The location of the tooltips is not consistent, either they are cut off, too far from the field it is referring to, or linger and cover-up subsequent tooltips.
- Tooltips do not work on the mobile version.

For further reference, review items # 2,4,5,6 from the [Heuristic Evaluation to Features](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=862594579) document, "Volunteers" tab.

### Action Items

- [x] Review / update the size of this issue.
- [x] Create mockups for suggested new tooltips.
- [x] Present options to the team.
- [ ] Update the [FOLA Design System](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2935%3A2) file with the selected design.

### Resources/Instructions
[FOLA Design System](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=2935%3A2)
[Heuristic Evaluation to Features](https://docs.google.com/spreadsheets/d/1UCoj5ecVQhOBAPNFvzOyySSeJFNtJ34Bx6Ti2cnLma0/edit#gid=862594579) 

### Parent Issue:
#320

**Comment by souronion** [comment] 2022-01-27 09:32
**I redesigned the tooltip along with some other components of the data entry form. Here are the changes:**

1. The title of every data field is now placed above the text box;
<img width="619" alt="截屏2022-01-27 下午5 19 13" src="https://user-images.githubusercontent.com/38329749/151329244-cf741f12-3650-4718-8bfb-b3ef9784dd44.png">

2. I used the help icon as an indicator of tooltips. If a data field has a tooltip, the icon will be displayed next to its title; 
<img width="680" alt="截屏2022-01-27 下午5 28 50" src="https://user-images.githubusercontent.com/38329749/151330887-2d833b1a-2d58-4b41-8791-ede789f9140d.png">

3. Every tooltip will point to its corresponding help icon, so it's clearer to users which data field it is referring to;
<img width="419" alt="截屏2022-01-27 下午5 29 43" src="https://user-images.githubusercontent.com/38329749/151331049-a64f4e1b-5881-4f01-8d12-7bfb3bf23f4b.png">

4. The "Confirmed" checkbox has been repositioned such that on a narrow screen, there will be more space for the textbox in each line;
5. I vaguely remember we had a discussion on changing the word "Confirmed" into something else. I used "Verified" in this mockup to show how it looks. We can talk about this further either in the comment section or at the team meeting.

**Here's how it looks on desktop.**

<img width="1315" alt="截屏2022-01-27 下午4 57 41" src="https://user-images.githubusercontent.com/38329749/151325568-a1b891c8-c4de-4514-be3d-8a7927de70aa.png">

**Here's how it looks on mobile.**

<img width="1203" alt="截屏2022-01-27 下午4 44 05" src="https://user-images.githubusercontent.com/38329749/151323209-cb214fed-0969-4a52-89e8-4e2635f4799e.png">

**Comment by souronion** [comment] 2022-01-27 10:05
Regarding the tooltip of "Verification Notes," I suggest that we display the instructions right next to the text box instead of putting it in a tooltip. Like this:

<img width="625" alt="截屏2022-01-27 下午6 00 30" src="https://user-images.githubusercontent.com/38329749/151336415-bb60f1c0-14b9-46ea-82a8-55c09f5b6100.png">

**Comment by souronion** [comment] 2022-02-18 01:54
Hi team, I made some changes to the tooltip design:

1. Use a help icon to indicate a tooltip;
2. When a user clicks/taps the help icon, display the tooltip and replace the help icon with a close icon;
3. For longer text, the user can scroll up and down to view the full content;
3. When the user clicks/taps the close icon, dismiss the tooltip.

I felt that a close icon might be useful here since some people may prefer to leave the tooltip open when they click away/edit the data field. For example, they may need to refer to the tooltip when writing verification notes. 

Here is a GIF to demonstrate the concept:
![Tooltip](https://user-images.githubusercontent.com/38329749/154600887-912c505b-068f-4fa5-b0ae-efcde1f723a7.gif)

**For data fields:**

1. Desktop
<img width="792" alt="截屏2022-02-18 上午9 49 45" src="https://user-images.githubusercontent.com/38329749/154602160-aff5fc2d-17ac-4be1-816f-bdaa45e4b114.png">

2. Mobile

<img width="787" alt="截屏2022-02-18 上午9 51 15" src="https://user-images.githubusercontent.com/38329749/154602311-ea050e17-0e44-4334-a280-18b74ca629e9.png">


Example of tooltips with long text (e.g. Verification Notes)

<img width="559" alt="截屏2022-02-18 上午9 52 27" src="https://user-images.githubusercontent.com/38329749/154602448-951f86f1-a400-49a9-a4f7-371b54381e12.png">


**For buttons:**

<img width="812" alt="截屏2022-02-18 上午9 53 27" src="https://user-images.githubusercontent.com/38329749/154602540-3aea7076-8539-4f5d-a597-ccea5b24f151.png">

**Comment by souronion** [comment] 2022-03-04 00:33
**Right now on a desktop, the tooltips are working pretty well except for the following two issues:**

1. Low contrast ratio makes the tooltip of verification notes hard to read;
2. The description of verification notes gets cut off because it's too long. 
   <img width="615" alt="截屏2022-03-04 上午6 12 53" src="https://user-images.githubusercontent.com/38329749/156661547-b3acfe93-8b87-4000-844a-8967a1a2ac1c.png">

**What we want to achieve:**
1. A quick fix for usability before we figure out how to rewrite the description/redesign the verification notes feature;
2. Make minimal changes to the rest of the tooltips given that they are working quite well.

**One recommendation is to use a popover window(a top layer), instead of a tooltip, to display the instructions.** 

- A user can trigger this top layer by clicking a help button;
- Scrolling is enabled to allow for longer text;
- "Close" button to dismiss the top layer.

**Note:** A user should be able to edit the form when the popover is open such that they can refer to the instructions while typing.

![Kapture 2022-03-04 at 07 03 59](https://user-images.githubusercontent.com/38329749/156667820-4efad063-8845-4c61-9c9b-1dffd143c6b9.gif)


---

**On mobile, other than the issues on verification notes, the main problem is that hovering does not work on mobile devices.**

One recommendation is to use help buttons to indicate tooltips **only on the mobile version**. 

- We can **reuse** the popover window described above to display instructions on mobile devices;
- When a user taps the help button, the popover gets triggered;
- When they tap the close button, the popover gets dismissed.

![Kapture 2022-03-04 at 07 59 32](https://user-images.githubusercontent.com/38329749/156673489-b47b1853-626f-4374-8ecc-cc22a8155e59.gif)

![Kapture 2022-03-04 at 08 31 29](https://user-images.githubusercontent.com/38329749/156676362-296f78ec-6a5b-49ad-8381-0a15b22b6b64.gif)

**Comment by souronion** [comment] 2022-03-04 01:04
Here's another small issue that is not directly related to tooltips.

When a textbox is empty, the title of the data field is displayed inside the box. This leads to two problems:
1. The form looks a little messy since the textboxes have different styles;
2. At first glance it is unclear to users which boxes are empty.

The recommended solution is to change the setting/style of the textboxes.
<img width="817" alt="截屏2022-03-04 上午9 04 07" src="https://user-images.githubusercontent.com/38329749/156679301-efebe764-625d-4134-901d-0b91070ca5b5.png">

**Comment by sei1122** [comment] 2022-09-30 17:27
As I remember, this design is done by @souronion. 
Probably it hasn't made a development issue.

**Comment by sei1122** [comment] 2023-01-12 02:21
@itsmylam worked on and here is final design
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=9097%3A16102&t=duH9vL8z8OIiEdiS-4

**Comment by fancyham** [comment] 2023-01-12 02:40
Figma: https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/FOLA-Design-System?node-id=9097%3A16102&t=duH9vL8z8OIiEdiS-4
PDF: [Finals.pdf](https://github.com/hackforla/food-oasis/files/10397697/Finals.pdf)

Desktop tooltip - single-line
![Screenshot 2023-01-11 at 4 38 09 PM](https://user-images.githubusercontent.com/3376957/211962857-b5720b62-1308-4395-a4ed-122c8a83eb44.jpg)

Desktop tooltip - large paragraph
![Screenshot 2023-01-11 at 4 38 04 PM](https://user-images.githubusercontent.com/3376957/211962859-b69f681f-136d-4fcc-b9d9-348265ee2c3f.jpg)

Mobile tooltip - single-line
![Screenshot 2023-01-11 at 4 38 18 PM](https://user-images.githubusercontent.com/3376957/211962854-4de1fce2-6bcb-4859-abb5-766885f6ba4b.jpg)

Mobile tooltip - large paragraph
![Screenshot 2023-01-11 at 4 38 31 PM](https://user-images.githubusercontent.com/3376957/211962846-e9d9fd88-9cde-4f01-b7c4-040fb9e39062.jpg)

**Comment by fancyham** [comment] 2023-01-12 02:46
@hanapotski @entrotech Not sure what the current process is but I tagged this issue 'Ready for dev lead' and put it on your board's triage pile AND assigned it to you.  That's probably overkill so let me know what you prefer!

Also, please comment here with your review notes — if we need to make changes or if it looks good.  Once you let me know it's moved into implementation, I'll close this issue out.

**Comment by staceyrebekahscott** [comment] 2023-01-14 02:33
@hanapotski @entrotech I triaged this issue and added it to your Backlog column. 

Still experimenting on this process for when issues are ready for Dev, so please let me know any feedback you have.

**Comment by fancyham** [comment] 2023-06-04 00:11
During development and preview, the design team felt the tooltip needed more differentiation from the background, so we tried a dropshadow and one of the darker variations.  After two rounds of voting, the dropshadow came out ahead by a good margin, so we’re going to go with that.

![image](https://github.com/hackforla/food-oasis/assets/3376957/b9806893-0258-4728-a73f-c16535cd01ec)

**Comment by fancyham** [comment] 2023-09-29 03:48
Done!  Thanks team!

**Closed by fancyham** 2023-09-29 03:48 UTC
Labels: Role: Design UI/UX, size: 3pt, P-Feature: Organization Form, PM: Volunteers, Ready for dev lead
