### ISSUE TITLE
Feature: Enhance Search Experience

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/food-oasis#2049] opened 2024-03-22 00:33 UTC
When clicking on "Back to List" button from detail list view, the user will be back at the top of the list. 

What should be the expected behavior when the user clicks on the back to list button?

**Current Behavior**

https://github.com/hackforla/food-oasis/assets/68657634/2e53225c-f4f5-4344-8567-aaa2278d3f20

**Comment by fancyham** [comment] 2024-03-29 00:23
This is a duplicate of
- #2056

**Closed by fancyham** 2024-03-29 00:23 UTC
Labels: Role: Design UI/UX, size: 2pt, Role: Product Management, P-Feature: Map, Sprint 05

**Comment by fancyham** [comment] 2024-03-29 00:24
Also renamed this issue to be more descriptive and to highlight that this was a regression (and so a bug)

was: "Feature: Enhance Search Experience"
