### ISSUE TITLE
Investigate "Update Failed" Bug Report on Organization Edit Form

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#481] opened 2020-06-04 00:04 UTC
### Overview
Volunteer Asharie and Jack Bedrosiaon have reported that on several occasions, the Organization Edit form will fail to save data entered, and display an "Update Failed message, losing the data they have entered.

### Action Items

- [ ] Interiew these users to see if we can identify a sequence of actions that reproduce this error.
- [ ] Fix it.

**Comment by entrotech** [comment] 2020-06-16 17:33
@jpmikesell Do we have any way to reproduce this bug?

**Comment by jpmikesell** [comment] 2020-06-16 17:44
let me reach out to them and also try to reproduce this myself

**Comment by Benbaillou** [comment] 2021-11-30 17:03
Hi - can we label the size please?

**Comment by Benbaillou** [comment] 2021-11-30 17:04
Hi - can we label the size please?

**Comment by staceyrebekahscott** [comment] 2022-08-31 05:48
Closing issue as outdated. 

This bug issue has been in the icebox since August 2020. If it is still a problem it would have been addressed.

**Closed by staceyrebekahscott** 2022-08-31 05:48 UTC
Labels: Release Note: Bug, Role: User Research, P-Feature: Organization Form, Missing: Size
