### ISSUE TITLE
Modify Landing Page Functionality

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#940] opened 2021-04-09 18:17 UTC
### Overview
The team decided to change the way the search criteria work on the landing page. Implement the following changes:

### Action Items
- [x] Add the "Learn about this site" link, which should open the About page.
- [x] Add the Magnifying Lens icon button. Pressing it should navigate to the Map page without specifying a location, which will, in turn use the default location (downtown LA for the Los Angeles tenant) as the "origin" for the search.
- [x] Remove "Current Location" from the drop-down box list as a choice. (Note that the "Search.js" react component is also used on the Map page, so we'll need to either adopt this behavior on the map page as well, or modify the code to only eliminate the "Current Location" choice when this component is used on the landing page.
- [x] Add the "Use my current location" button. When this is pressed and the user's browser is set to allow location detection, set the "origin" to the user's current location, execute the search, and navigate to the Map page.  If the user's browser is set to dis-allow location detection, see if you can prompt them to set the browser to allow detecting their current location. Ideally, if they disallow location, they will be returned to the landing page, but if they allow location, the location will be determined, the serach will be executed using that location as the "origin", and they should then be taken to the Map page to see the results.

### Resources/Instructions
Refer to this Figma file (the Page called "2020-03 Landing page flow experiment") . Options A and B show the search dialog wireframe.
https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=2743%3A7824

**Comment by sameergautam** [comment] 2021-07-16 01:31
This issue seems to be mostly about search. @gigicobos to label it accordingly.

**Comment by sameergautam** [comment] 2021-07-22 13:07
I can confirm the actions listed to be available on the landing page. Hence, closing this issue.

**Closed by sameergautam** 2021-07-22 13:07 UTC
Labels: 3pt, 8pt, P-Feature: Landing Page, dev: front-end, enhancement
