### ISSUE TITLE
Feature request: Update metadata on FOLA's static pages

### ISSUE THREAD

**Issue by jelenaUX** [hackforla/food-oasis#1662] opened 2023-04-29 23:56 UTC
### Context
The metadata on FOLA's static pages is out of date. Metadata is either wrong or does not address visitors who may be looking for food organizations.

### How is it now?
The current metadata seems to address institutional partners ("donors" and "food outlets") rather than individual food seekers.
![Screen Shot 2023-04-29 at 7 33 24 PM](https://user-images.githubusercontent.com/113402302/235328275-a4f973a5-540c-41ec-9171-f5124b698f09.png)
 
### Proposed new feature
Update the metadata on FOLA website:
- [ ] Complete more in-depth competitive SEO research.
- [ ] Collaborate with FOLA’s writing team to rephrase the descriptions of FOLA’s static pages.

### References:
Quick competitive SEO analysis brings up terms that may be applicable to FOLA. For example, my quick search for "food pantry LA" included results such as "Our map shows resources [available] in real time." "Enter your address to see local [free and subsidized food resources]."   
![Screen Shot 2023-04-29 at 7 46 50 PM](https://user-images.githubusercontent.com/113402302/235328718-84e1ca9b-3ea7-4f61-bdeb-02b1c5b1c157.png)

**Comment by qiqicodes** [comment] 2024-04-11 23:40
Duplicated issue #1976

**Comment by fancyham** [comment] 2024-06-13 00:10
Duplicate of #1976

**Closed by fancyham** 2024-06-13 00:10 UTC
Labels: Research, Role: Business Analysis / Product, Role: Copywriting, size: 2pt, Role: Product Management, Role: User Research, Feature: Usability, PM: Food Seekers, Website and Marketing Content, Social Media and Marketing
