### ISSUE TITLE
Replace the wording and images on the Hawaii static pages with appropriate content.

### ISSUE THREAD

**Issue by entrotech** [hackforla/food-oasis#752] opened 2020-10-22 17:33 UTC
### Overview
Replace the wording and images on the Hawaii static pages with appropriate content.

### Action Items
- [ ] Adapt the /StaticPagesHI/About.js page
- [ ] Adapt the /StaticPagesHI/Donate.js page
- [ ] Adapt the /StatidPagesHI/Faq.js page

### Resources/Instructions
Ultimately, this should come from Ms. Jay Purvis at Aloha Harvest. As of 10/22/20, she is busy with a Salesforce implementation at Aloha Harvest, but the intent is to go live with the Hawaii tenant before Thanksgiving 2020.

**Comment by tekielee** [comment] 2021-03-12 21:31
Is it to late to update this? If not, where do I get the content?

**Comment by entrotech** [comment] 2021-03-24 00:55
This is assigned to Suchanra Thapa - need to add him to Hack for LA Github and repo

**Comment by sthapa** [comment] 2021-06-15 04:53
Updated the wording based on the document Leslie provided and the changes have landed on the dev site.  I believe it's completed but we're just waiting for Leslie to get back to us.

**Comment by stdyrm** [comment] 2021-06-27 01:49
Made a PR for importing logos. should be maintainable if we add more tenants: #999

**Comment by stdyrm** [comment] 2021-07-13 03:59
No rush, but I also wanted to mention that either because of my vpn or I may have rejected initial gelocation request, when I was working on this tenantId config automatically set to 1 (LA). I hardcoded a tenantId = 3 when working on this and deleted after. In production will users just use the URL to go to LA/HI/etc. and the map will default to that location?

**Comment by stdyrm** [comment] 2021-08-22 10:10
Merged in #999 

Leaving issue open, will close after Aloha Harvest reviews

**Comment by stdyrm** [comment] 2021-09-07 11:57
> The Hawaii header seems too tall (taller than the LA site and hamburger menu in upper right) on both desktop and mobile.
> 
> Can we find a shorter Aloha Harvest logo we can use, or perhaps we should shrink the logo so that the header doesn't take up so much space? Maybe drop the tagline under the logo?

No problem, I can crop the Hawaii logo without tagline and adjust the styles a bit. However, when I check my local and the LA live site, I get a taller logo than the one you show? Hawaii Header w/o tagline is about 77px (I can make this shorter) and the tall LA header is about 107px. I think the short LA header you're referencing is about 50px high. 

Before I adjust the styles, just want to doublecheck if the mobile LA header should be tall or short? Adjusting min/max height might impact the tall LA logo.
 
![Screen Shot 2021-09-07 at 1 08 12 AM](https://user-images.githubusercontent.com/17044124/132335577-876664e7-7639-465e-8711-dd02c9d10e18.png)  ![Screen Shot 2021-09-07 at 1 08 36 AM](https://user-images.githubusercontent.com/17044124/132335856-08dc27ba-6099-4963-9589-296eea7cb5bb.png)

**Comment by fancyham** [comment] 2021-09-09 04:26
Weird!  I wonder if the new taller logos are because of a new pull, specifically the one supporting these logos?  I got my screenshots about 2 weeks ago and believe that what was on the dev sites was moved to production since then, in which case the tall logos on the organizations view might be more of a bug report ;) @entrotech ?

**Comment by stdyrm** [comment] 2021-09-09 09:40
Hmm did the /organizations and other pages have a different header logo? Is there really a reason to have a short logo in the /organization and a tall one on the other pages? If planning to switch to short, maybe we can make logo the same on all pages

**Comment by fancyham** [comment] 2021-09-09 18:28
I believe so.  I don’t know if there’s been any thought to the short vs tall logos on all pages but sometimes there are multiple versions of a logo for different uses.  This might be a good example of when that’d be useful.  

The tall logo on the HI landing page is pretty cool and then a shorter one on the /organizations could work really well.

(BTW, what’s the short Aloha Harvest logo look like?  Just the text part?  I couldn’t find an official version so we can try to make one but should expect that it’ll will change later to an official one once we’re back in touch)

Could you make it so that the landing page and /organizations can draw from different logo files for this type of case?  Sometimes they’ll be the same but I can imagine cases where they’re different.

**Comment by fancyham** [comment] 2021-09-10 02:59
@entrotech Mentioned that the logo on the /organizations pages may have been responsive?  Maybe worth checking old code if that was the case, in case it's a regression.

Oh!  A possible clue: I just noticed that a different FO LA logo loads depending on if the site is loaded on a smartphone (tall green box logo) or loaded on a larger screen (horizontal word logo with carrot).  Give it a try!  

Whatever logo loads stays even as I change screen dimensions.  That might be the bug?

(I did this in Safari in responsive mode)

**Comment by stdyrm** [comment] 2021-09-10 12:03
Okay, for landing page, you mean the logo in the middle, right? But the header logo will be the same on all routes? That shouldn't be a problem.

I don't think there's a separate short Aloha Harvest logo. Sorry for the confusion, I was referring to the one that cropped off the tagline as the "short version"

Yeah, it loads a separate file. You'd need to refresh the page for the new logo to load. There may be better ways to make it more responsive, but I think it's the same as some previous sites I've worked on. I think most users would either load on mobile or on desktop and generally wouldn't resize by that degree, but up to you whether we can prioritize that or not.

Just let me know about what you want to do with the tall logo in the header on mobile. Depending on that, I can try to resize the Aloha Harvest logo to match similar dimensions on mobile and desktop.

**Comment by fancyham** [comment] 2021-09-10 19:23
Yup, the landing page is the one with the map background and the dialog front and center.

FO LA: The one that looks like this
![image](https://user-images.githubusercontent.com/3376957/132906433-50302720-2ae3-416b-adc5-f8585144aa4e.jpeg)

FO HI: The one that looks like this
![image](https://user-images.githubusercontent.com/3376957/132906404-75bc90c4-f9f9-467f-8beb-7bda10cbfae2.png)

Headers for the routes
FO LA : use the logo that looks like this: https://foodoasis.la/static/media/foodoasis.b87c773b.svg (if it's a SVG, don't we just specify the height?)
FO HI : Use the logo without the tagline 
![image](https://user-images.githubusercontent.com/3376957/132906340-cb602774-8f60-49e0-939e-bd8431cd475e.jpeg)

Thanks for the explanation about resizing and loading the logo.  Yeah, don't need to reload a different image on resize (and besides I think we'd be using the same image now.

**Comment by stdyrm** [comment] 2021-09-11 21:33
Sounds good. 

- Remove stacked LA logo from Header (keeping file in folder)
- Use Hawaii no tagline logo for Header
- Use Hawaii w/tagline logo for landing page

> FO LA : use the logo that looks like this: https://foodoasis.la/static/media/foodoasis.b87c773b.svg (if it's a SVG, don't we just specify the height?)

Yes, just need to make it responsive, because of aspect ratios. 175px maxWidth restrains LA logo, but makes HI logo massive, opposite true of 48px maxHeight.

One question: is the tagline "Find free food in _____" necessary on the mobile header? Just looks a bit crowded, and desktop version doesn't have it or any more information than mobile (ie does the tagline clarify anything on mobile, since mobile version doesn't remove any information from desktop version). I'm wondering if it was added before to distinguish LA from Hawaii or other tenants, but not sure if we still need. I'd leave the code, and try to allow taglineText to be inserted as a prop instead.

**Comment by fancyham** [comment] 2021-09-12 05:32
Good question about the "Find free food in…" tag line — didn't realize it was only on the mobile site, too.

Could you open an issue / question about it?  

I think that's a good catch and worth bringing up — for example, if we're going to have it, shouldn't it be on the desktop site where there's more space? :)

**Comment by stdyrm** [comment] 2021-09-12 08:24
In my last commit, I moved the tagline text to a config file, so each tenant can choose whatever they want. This is imported into App.js and added as props into the Header component. I deleted Hawaii's text, but left LA and other tenants intact. If nobody has objections with this commit, I don't think it'll be necessary to open a new issue. 

Actually I realized later that the tagline text is on the desktop, but only on the map page and not on the header. It appears in the same area as the search bar. I still don't think it's really necessary but the tenants can decide for their respective apps

**Comment by entrotech** [comment] 2021-09-14 03:47
The tagline is considered important so there is some context as to what the app is for, if the user is given a link that takes them straight to the map page. 

If you look at the Figma file here https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=1647%3A3660 Under the Mobile Mockups page, it shows what the header on a mobile device looked like on a mobile device.   Here is a relevant screen cap from the Figma file:

![image](https://user-images.githubusercontent.com/9939032/133191365-242a0129-d1d2-4145-ab51-2ff673d273d1.png)

The mobile header should look like this, except that issue #898 changed the wording of the header, and Issuse #941 modified the exact design of the stacked logo to remove "LA", so it could be used across most tenants.

The reasoning for this design is: On devices less than 768 pixels wide, we need all the room on the filter div for filter controls, but wanted to keep the tag line, so the tag line moves up to the header div with the logo and hamburger menu icon. To make this work on the smallest devices with enough horizontal space, we replaced the desktop app logo with the stacked logo.  When we did so, the styling of the logo set its height to 45 px. This gave us horizontal room for the logo, tagline and Hamburger menu logo in the header.  It looks like an inadvertent change made the stacked logo much taller for the LA tenant.

The design for a device wider than 768 pixels is supposed to use the wider logo, and have the tagline on the filter div under the header with the logo and menu, since the designers decided that there is enough horizontal room on the filter div, and it give the design a better balance - like this:
![image](https://user-images.githubusercontent.com/9939032/133190460-d239765a-ac55-482f-b4a4-d69851ac282d.png)

If Hawaii wants a different header design, that's fine, but the header should be reverted back to the behavior above for the LA and other tenants.

**Comment by stdyrm** [comment] 2021-09-14 04:38
Thanks, makes sense. I actually removed the stacked logo in my present PR; I can make changes below. Let me know if I should add or change anything.

- Restore stacked LA logo (but set max height = 45px)
- Restore tagline(?) - as mentioned in my last comment, I rearranged the tagline so it can be set independently by each tenant in a config file. Maybe I can keep this change, but also have the tagline in the desktop version dependent on the same config file

**Comment by stdyrm** [comment] 2021-09-14 08:47
@entrotech @fancyham restored stacked logos and taglines (left taglines in the constants file so they're passed as props from App.js)

cc @sthapa

**Comment by stdyrm** [comment] 2021-10-05 05:35
@entrotech @fancyham @sthapa per our 10/4 meeting, we can hold off on closing this issue depending on the future involvement of AH. If a rollback is needed, I'll do it on this same ticket.

**Comment by stdyrm** [comment] 2021-11-01 09:49
@entrotech @fancyham @sthapa revised HI static pages per Aloha Harvest's suggestions. See PR #1083

**Comment by fancyham** [comment] 2021-11-20 00:33
@stdyrm Hey there, is this done and can it be closed?

**Comment by stdyrm** [comment] 2021-11-20 08:19
@fancyham Yes, thanks it can be closed.

**Comment by fancyham** [comment] 2021-11-20 18:29
Thanks!

**Closed by fancyham** 2021-11-20 18:29 UTC
Labels: Role: Front-end, 2pt, Partner: Code for Hawaii, P-Feature: Tenant Specific Other
