### ISSUE TITLE
Improve landing page (Feb 23)

### ISSUE THREAD

**Issue by ktjnyc** [hackforla/food-oasis#868] opened 2021-02-24 02:39 UTC
Overview
As a food seeker I need a simple landing page so that I can find food.

Action Items
- [x] Document the points of friction in a comment below (eg having to click the magnifying glass after entering address) #892 
- [x] Create Simple mock up of the map page
- [ ] Determine potential options for usability study
- [ ] Draft message regarding why we are doing the usability study  
- [ ] Create the usability study link
- [ ] Send to Olivia to @channel for general slack 

Resources/Instructions
[Figma](https://www.figma.com/file/D3oq9QOXl0rFkwrEUJbABs/Fola-Design-System?node-id=2591%3A0)
[John's Dev site ](https://devla.foodoasis.net/)
Update this with usability hub link
[Link to document with usability items](https://docs.google.com/document/d/1dDx2hbCGQZlfeGyA8g7DtahnlomIrgD8amisqHAQpDg/edit)
[Link to 2021 UX study](https://drive.google.com/file/d/1FyIWm4SGqgopm_LESiChPoWFDP_TI2Z_/view?usp=sharing)

**Comment by cindywongg** [comment] 2021-03-03 00:16
Points of friction: 
- clicking the magnifying glass after entering the address on the landing page 
- landing page takes a while to load due to the high resolution background images
- whether or not user will understand the purpose of the website if the user is taken straight to the map page

**Comment by fancyham** [comment] 2021-07-30 02:12
Seems to be a duplicate of #862 .  Closing.

**Closed** 2021-07-30 02:57 UTC
Labels: Role: Design UI/UX, p-feature: Map, Missing: Milestone, complexity: missing, Interface: Food Seeker, size: 2pt
